# Generated by Django 4.1 on 2022-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(default="", max_length=50)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("mdt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
